// {
//   type: "RouteDetail",
//   data: {
//     uuid: "38e4047c-7a67-4c49-9e3b-cb40a22d8bd3",
//     routeId: "",
//   },
//   config: {},
//   name: "38e4047c-7a67-4c49-9e3b-cb40a22d8bd3",
// },

export default {
  key: "PageConfig",
  showLeftToolbar: true,
  showStopToolbar: true,
  showClock: true,
  showHelpDialog: false,
  time: 28440,
  speed: 0,
  minTime: 0,
  maxTime: 88200,
  center: [12634435.302642914, 2645511.8325935453],
  zoom: 14,
  rotation: 0,
  pitch: 90,
  activeNames: ["PublicTransit", "MotorizedTravel", "CarTravel", "Build3D", "Network", "Activity3D", "GeoJSON", "Parking", "TrafficRegionAnalysis"],
  toolbarActiveName: "PublicTransit",
  map_style_name: "",
  language: "zh-CN",

  publicTransitConfig: { showLayer: false, lock2D: false, stopColor: "#2656C6", stopScale: 2, selectStop: false },
  PublicTransitToolbar: { sreach: {}, params: {}, activeName: "", list: [] },

  motorizedTravelConfig: { showLayer: false, lock2D: false, maxVehicleNum: 20000, modelSize: 3, showBus3DLayer: true, showSubway3DLayer: true, lockSelectVehicle: true },
  carTravelConfig: { showLayer: false, lock2D: false, lockSelectVehicle: true, showBus3DLayer: true, showSubway3DLayer: true, showCar3DLayer: true, maxVehicleNum: 20000, modelSize: 3 },
  MotorizedTravelToolbar: { sreach: {}, params: {}, activeName: "", list: [] },

  build3DConfig: { showLayer: false, lock2D: false, buildColor: "#838385", buildOpacity: 80 },
  Build3DToolbar: { sreach: {}, params: {}, activeName: "", list: [] },

  networkConfig: { showLayer: false, lock2D: false, colors: 0, width: 1, videoIconWidth: 10, offset: 0, color: "#E9CDAA", showNode: false, showVideoIcon: false },
  NetworkToolbar: { sreach: {}, params: {}, activeName: "", list: [] },

  activity3DConfig: {
    showLayer: false,
    lock2D: false,
    color: "#5470c6",
    scale: 1,
    maxNum: 10000,
    showColorTypeTable: false,
    colorType: "activity",
    activityTypeList: [
      { name: "home", color: "#5470c6" },
      { name: "pickup/dropoff", color: "#91cc75" },
      { name: "pickup", color: "#fac858" },
      { name: "work", color: "#ee6666" },
      { name: "school", color: "#73c0de" },
      { name: "other", color: "#3ba272" },
      { name: "leisure", color: "#fc8452" },
      { name: "errand", color: "#9a60b4" },
    ],
    legTypeList: [
      { name: "car", color: "#5470c6" },
      { name: "pt", color: "#91cc75" },
      { name: "bus", color: "#fac858" },
      { name: "subway", color: "#ee6666" },
      { name: "walk", color: "#73c0de" },
      { name: "bike", color: "#3ba272" },
    ],
  },
  Activity3DToolbar: { sreach: {}, params: {}, activeName: "", list: [] },

  geoJSONConfig: { showLayer: false, lock2D: false, geoJSONList: [] },

  parkingConfig: {
    showLayer: false,
    lock2D: false,
    color: "#5470c6",
    scale: 1,
    maxNum: 10000,
    showColorTypeTable: false,
    colorType: "activity",
    activityTypeList: [
      { name: "home", color: "#5470c6" },
      { name: "pickup/dropoff", color: "#91cc75" },
      { name: "pickup", color: "#fac858" },
      { name: "work", color: "#ee6666" },
      { name: "school", color: "#73c0de" },
      { name: "other", color: "#3ba272" },
      { name: "leisure", color: "#fc8452" },
      { name: "errand", color: "#9a60b4" },
    ],
    legTypeList: [
      { name: "car", color: "#5470c6" },
      { name: "pt", color: "#91cc75" },
      { name: "bus", color: "#fac858" },
      { name: "subway", color: "#ee6666" },
      { name: "walk", color: "#73c0de" },
      { name: "bike", color: "#3ba272" },
    ],
    geoJSON: null,
  },
  ParkingToolbar: { sreach: {}, params: {}, activeName: "", list: [] },

  trafficRegionAnalysisConfig: { showLayer: false, lock2D: false },
  TrafficRegionAnalysisToolbar: { sreach: {}, params: {}, activeName: "", list: [] },

  routePlanningConfig: {
    showPoint: true,
    pointColor: "#FF6161",
    pointSize: 1.5,
    showRoute: true,
    routeSize: 5,
    routeColor: "#409BFC",
    showNetwork: false,
    showFlyableArea: false,
    networkMode: [],
    // "networkModeList": ["bus", "car", "artificial", "stopFacilityLink", "tram", "subway", "ferry"],
    networkSize: 5,
    showUAVPage: false,
    lockUAV: false,
    uavSize: 3,
  },
  RoutePlanningToolbar: { sreach: {}, params: {}, activeName: "", list: [] },

  
  cityUpdateAreaConfig: {
  },
  CityUpdateAreaToolbar: { sreach: {}, params: {}, activeName: "", list: [] },
};
